package client

import (
	"math/rand"
	"time"

	"github.com/SlothNinja/sn/v3"
	"github.com/elliotchance/pie/v2"
)

var myRandomSource = rand.NewSource(time.Now().UnixNano())

// shuffled deck for number players
func deckFor(numPlayers int) []card {
	var d []card
	switch numPlayers {
	case 2:
		d = []card{
			card{oneRank, trumps, sn.NoPID, true},
			card{twoRank, trumps, sn.NoPID, true},
			card{threeRank, trumps, sn.NoPID, true},
			card{fourRank, trumps, sn.NoPID, true},
			card{fiveRank, trumps, sn.NoPID, true},
			card{sixRank, trumps, sn.NoPID, true},
			card{sevenRank, trumps, sn.NoPID, true},
			card{tenRank, hearts, sn.NoPID, true}, card{tenRank, clubs, sn.NoPID, true},
			card{tenRank, spades, sn.NoPID, true}, card{tenRank, diamonds, sn.NoPID, true},
			card{valetRank, hearts, sn.NoPID, true}, card{valetRank, clubs, sn.NoPID, true},
			card{valetRank, spades, sn.NoPID, true}, card{valetRank, diamonds, sn.NoPID, true},
			card{cavalierRank, hearts, sn.NoPID, true}, card{cavalierRank, clubs, sn.NoPID, true},
			card{cavalierRank, spades, sn.NoPID, true}, card{cavalierRank, diamonds, sn.NoPID, true},
			card{dameRank, hearts, sn.NoPID, true}, card{dameRank, clubs, sn.NoPID, true},
			card{dameRank, spades, sn.NoPID, true}, card{dameRank, diamonds, sn.NoPID, true},
			card{roiRank, hearts, sn.NoPID, true}, card{roiRank, clubs, sn.NoPID, true},
			card{roiRank, spades, sn.NoPID, true}, card{roiRank, diamonds, sn.NoPID, true},
			card{sixteenRank, trumps, sn.NoPID, true},
			card{seventeenRank, trumps, sn.NoPID, true},
			card{eighteenRank, trumps, sn.NoPID, true},
			card{nineteenRank, trumps, sn.NoPID, true},
			card{twentyRank, trumps, sn.NoPID, true},
			card{twentyoneRank, trumps, sn.NoPID, true},
			card{excuseRank, trumps, sn.NoPID, true},
		}
	case 3:
		d = []card{
			card{oneRank, trumps, sn.NoPID, true},
			card{twoRank, trumps, sn.NoPID, true},
			card{threeRank, trumps, sn.NoPID, true},
			card{fourRank, trumps, sn.NoPID, true},
			card{fiveRank, trumps, sn.NoPID, true},
			card{sixRank, trumps, sn.NoPID, true},
			card{sevenRank, trumps, sn.NoPID, true},
			card{eightRank, trumps, sn.NoPID, true},
			card{nineRank, trumps, sn.NoPID, true},
			card{tenRank, trumps, sn.NoPID, true},
			card{tenRank, hearts, sn.NoPID, true}, card{tenRank, clubs, sn.NoPID, true},
			card{tenRank, spades, sn.NoPID, true}, card{tenRank, diamonds, sn.NoPID, true},
			card{elevenRank, trumps, sn.NoPID, true},
			card{valetRank, hearts, sn.NoPID, true}, card{valetRank, clubs, sn.NoPID, true},
			card{valetRank, spades, sn.NoPID, true}, card{valetRank, diamonds, sn.NoPID, true},
			card{twelveRank, trumps, sn.NoPID, true},
			card{cavalierRank, hearts, sn.NoPID, true}, card{cavalierRank, clubs, sn.NoPID, true},
			card{cavalierRank, spades, sn.NoPID, true}, card{cavalierRank, diamonds, sn.NoPID, true},
			card{thirteenRank, trumps, sn.NoPID, true},
			card{dameRank, hearts, sn.NoPID, true}, card{dameRank, clubs, sn.NoPID, true},
			card{dameRank, spades, sn.NoPID, true}, card{dameRank, diamonds, sn.NoPID, true},
			card{fourteenRank, trumps, sn.NoPID, true},
			card{roiRank, hearts, sn.NoPID, true}, card{roiRank, clubs, sn.NoPID, true},
			card{roiRank, spades, sn.NoPID, true}, card{roiRank, diamonds, sn.NoPID, true},
			card{fifteenRank, trumps, sn.NoPID, true},
			card{sixteenRank, trumps, sn.NoPID, true},
			card{seventeenRank, trumps, sn.NoPID, true},
			card{eighteenRank, trumps, sn.NoPID, true},
			card{nineteenRank, trumps, sn.NoPID, true},
			card{twentyRank, trumps, sn.NoPID, true},
			card{twentyoneRank, trumps, sn.NoPID, true},
			card{excuseRank, trumps, sn.NoPID, true},
		}
	case 4:
		d = []card{
			card{oneRank, trumps, sn.NoPID, true},
			card{twoRank, trumps, sn.NoPID, true},
			card{threeRank, trumps, sn.NoPID, true},
			card{fourRank, trumps, sn.NoPID, true},
			card{fiveRank, trumps, sn.NoPID, true},
			card{sixRank, trumps, sn.NoPID, true},
			card{sixRank, spades, sn.NoPID, true},
			card{sevenRank, trumps, sn.NoPID, true},
			card{sevenRank, hearts, sn.NoPID, true}, card{sevenRank, clubs, sn.NoPID, true},
			card{sevenRank, spades, sn.NoPID, true}, card{sevenRank, diamonds, sn.NoPID, true},
			card{eightRank, trumps, sn.NoPID, true},
			card{eightRank, hearts, sn.NoPID, true}, card{eightRank, clubs, sn.NoPID, true},
			card{eightRank, spades, sn.NoPID, true}, card{eightRank, diamonds, sn.NoPID, true},
			card{nineRank, trumps, sn.NoPID, true},
			card{nineRank, hearts, sn.NoPID, true}, card{nineRank, clubs, sn.NoPID, true},
			card{nineRank, spades, sn.NoPID, true}, card{nineRank, diamonds, sn.NoPID, true},
			card{tenRank, trumps, sn.NoPID, true},
			card{tenRank, hearts, sn.NoPID, true}, card{tenRank, clubs, sn.NoPID, true},
			card{tenRank, spades, sn.NoPID, true}, card{tenRank, diamonds, sn.NoPID, true},
			card{elevenRank, trumps, sn.NoPID, true},
			card{valetRank, hearts, sn.NoPID, true}, card{valetRank, clubs, sn.NoPID, true},
			card{valetRank, spades, sn.NoPID, true}, card{valetRank, diamonds, sn.NoPID, true},
			card{twelveRank, trumps, sn.NoPID, true},
			card{cavalierRank, hearts, sn.NoPID, true}, card{cavalierRank, clubs, sn.NoPID, true},
			card{cavalierRank, spades, sn.NoPID, true}, card{cavalierRank, diamonds, sn.NoPID, true},
			card{thirteenRank, trumps, sn.NoPID, true},
			card{dameRank, hearts, sn.NoPID, true}, card{dameRank, clubs, sn.NoPID, true},
			card{dameRank, spades, sn.NoPID, true}, card{dameRank, diamonds, sn.NoPID, true},
			card{fourteenRank, trumps, sn.NoPID, true},
			card{roiRank, hearts, sn.NoPID, true}, card{roiRank, clubs, sn.NoPID, true},
			card{roiRank, spades, sn.NoPID, true}, card{roiRank, diamonds, sn.NoPID, true},
			card{fifteenRank, trumps, sn.NoPID, true},
			card{sixteenRank, trumps, sn.NoPID, true},
			card{seventeenRank, trumps, sn.NoPID, true},
			card{eighteenRank, trumps, sn.NoPID, true},
			card{nineteenRank, trumps, sn.NoPID, true},
			card{twentyRank, trumps, sn.NoPID, true},
			card{twentyoneRank, trumps, sn.NoPID, true},
			card{excuseRank, trumps, sn.NoPID, true},
		}
	case 5:
		d = []card{
			card{oneRank, trumps, sn.NoPID, true},
			card{twoRank, trumps, sn.NoPID, true},
			card{threeRank, trumps, sn.NoPID, true},
			card{threeRank, clubs, sn.NoPID, true}, card{threeRank, spades, sn.NoPID, true},
			card{fourRank, trumps, sn.NoPID, true},
			card{fourRank, hearts, sn.NoPID, true}, card{fourRank, clubs, sn.NoPID, true},
			card{fourRank, spades, sn.NoPID, true}, card{fourRank, diamonds, sn.NoPID, true},
			card{fiveRank, trumps, sn.NoPID, true},
			card{fiveRank, hearts, sn.NoPID, true}, card{fiveRank, clubs, sn.NoPID, true},
			card{fiveRank, spades, sn.NoPID, true}, card{fiveRank, diamonds, sn.NoPID, true},
			card{sixRank, trumps, sn.NoPID, true},
			card{sixRank, hearts, sn.NoPID, true}, card{sixRank, clubs, sn.NoPID, true},
			card{sixRank, spades, sn.NoPID, true}, card{sixRank, diamonds, sn.NoPID, true},
			card{sevenRank, trumps, sn.NoPID, true},
			card{sevenRank, hearts, sn.NoPID, true}, card{sevenRank, clubs, sn.NoPID, true},
			card{sevenRank, spades, sn.NoPID, true}, card{sevenRank, diamonds, sn.NoPID, true},
			card{eightRank, trumps, sn.NoPID, true},
			card{eightRank, hearts, sn.NoPID, true}, card{eightRank, clubs, sn.NoPID, true},
			card{eightRank, spades, sn.NoPID, true}, card{eightRank, diamonds, sn.NoPID, true},
			card{nineRank, trumps, sn.NoPID, true},
			card{nineRank, hearts, sn.NoPID, true}, card{nineRank, clubs, sn.NoPID, true},
			card{nineRank, spades, sn.NoPID, true}, card{nineRank, diamonds, sn.NoPID, true},
			card{tenRank, trumps, sn.NoPID, true},
			card{tenRank, hearts, sn.NoPID, true}, card{tenRank, clubs, sn.NoPID, true},
			card{tenRank, spades, sn.NoPID, true}, card{tenRank, diamonds, sn.NoPID, true},
			card{elevenRank, trumps, sn.NoPID, true},
			card{valetRank, hearts, sn.NoPID, true}, card{valetRank, clubs, sn.NoPID, true},
			card{valetRank, spades, sn.NoPID, true}, card{valetRank, diamonds, sn.NoPID, true},
			card{twelveRank, trumps, sn.NoPID, true},
			card{cavalierRank, hearts, sn.NoPID, true}, card{cavalierRank, clubs, sn.NoPID, true},
			card{cavalierRank, spades, sn.NoPID, true}, card{cavalierRank, diamonds, sn.NoPID, true},
			card{thirteenRank, trumps, sn.NoPID, true},
			card{dameRank, hearts, sn.NoPID, true}, card{dameRank, clubs, sn.NoPID, true},
			card{dameRank, spades, sn.NoPID, true}, card{dameRank, diamonds, sn.NoPID, true},
			card{fourteenRank, trumps, sn.NoPID, true},
			card{roiRank, hearts, sn.NoPID, true}, card{roiRank, clubs, sn.NoPID, true},
			card{roiRank, spades, sn.NoPID, true}, card{roiRank, diamonds, sn.NoPID, true},
			card{fifteenRank, trumps, sn.NoPID, true},
			card{sixteenRank, trumps, sn.NoPID, true},
			card{seventeenRank, trumps, sn.NoPID, true},
			card{eighteenRank, trumps, sn.NoPID, true},
			card{nineteenRank, trumps, sn.NoPID, true},
			card{twentyRank, trumps, sn.NoPID, true},
			card{twentyoneRank, trumps, sn.NoPID, true},
			card{excuseRank, trumps, sn.NoPID, true},
		}
	case 6:
		d = []card{
			card{oneRank, trumps, sn.NoPID, true},
			card{oneRank, hearts, sn.NoPID, true}, card{oneRank, clubs, sn.NoPID, true},
			card{oneRank, spades, sn.NoPID, true}, card{oneRank, diamonds, sn.NoPID, true},
			card{twoRank, trumps, sn.NoPID, true},
			card{twoRank, hearts, sn.NoPID, true}, card{twoRank, clubs, sn.NoPID, true},
			card{twoRank, spades, sn.NoPID, true}, card{twoRank, diamonds, sn.NoPID, true},
			card{threeRank, trumps, sn.NoPID, true},
			card{threeRank, hearts, sn.NoPID, true}, card{threeRank, clubs, sn.NoPID, true},
			card{threeRank, spades, sn.NoPID, true}, card{threeRank, diamonds, sn.NoPID, true},
			card{fourRank, trumps, sn.NoPID, true},
			card{fourRank, hearts, sn.NoPID, true}, card{fourRank, clubs, sn.NoPID, true},
			card{fourRank, spades, sn.NoPID, true}, card{fourRank, diamonds, sn.NoPID, true},
			card{fiveRank, trumps, sn.NoPID, true},
			card{fiveRank, hearts, sn.NoPID, true}, card{fiveRank, clubs, sn.NoPID, true},
			card{fiveRank, spades, sn.NoPID, true}, card{fiveRank, diamonds, sn.NoPID, true},
			card{sixRank, trumps, sn.NoPID, true},
			card{sixRank, hearts, sn.NoPID, true}, card{sixRank, clubs, sn.NoPID, true},
			card{sixRank, spades, sn.NoPID, true}, card{sixRank, diamonds, sn.NoPID, true},
			card{sevenRank, trumps, sn.NoPID, true},
			card{sevenRank, hearts, sn.NoPID, true}, card{sevenRank, clubs, sn.NoPID, true},
			card{sevenRank, spades, sn.NoPID, true}, card{sevenRank, diamonds, sn.NoPID, true},
			card{eightRank, trumps, sn.NoPID, true},
			card{eightRank, hearts, sn.NoPID, true}, card{eightRank, clubs, sn.NoPID, true},
			card{eightRank, spades, sn.NoPID, true}, card{eightRank, diamonds, sn.NoPID, true},
			card{nineRank, trumps, sn.NoPID, true},
			card{nineRank, hearts, sn.NoPID, true}, card{nineRank, clubs, sn.NoPID, true},
			card{nineRank, spades, sn.NoPID, true}, card{nineRank, diamonds, sn.NoPID, true},
			card{tenRank, trumps, sn.NoPID, true},
			card{tenRank, hearts, sn.NoPID, true}, card{tenRank, clubs, sn.NoPID, true},
			card{tenRank, spades, sn.NoPID, true}, card{tenRank, diamonds, sn.NoPID, true},
			card{elevenRank, trumps, sn.NoPID, true},
			card{valetRank, hearts, sn.NoPID, true}, card{valetRank, clubs, sn.NoPID, true},
			card{valetRank, spades, sn.NoPID, true}, card{valetRank, diamonds, sn.NoPID, true},
			card{twelveRank, trumps, sn.NoPID, true},
			card{cavalierRank, hearts, sn.NoPID, true}, card{cavalierRank, clubs, sn.NoPID, true},
			card{cavalierRank, spades, sn.NoPID, true}, card{cavalierRank, diamonds, sn.NoPID, true},
			card{thirteenRank, trumps, sn.NoPID, true},
			card{dameRank, hearts, sn.NoPID, true}, card{dameRank, clubs, sn.NoPID, true},
			card{dameRank, spades, sn.NoPID, true}, card{dameRank, diamonds, sn.NoPID, true},
			card{fourteenRank, trumps, sn.NoPID, true},
			card{roiRank, hearts, sn.NoPID, true}, card{roiRank, clubs, sn.NoPID, true},
			card{roiRank, spades, sn.NoPID, true}, card{roiRank, diamonds, sn.NoPID, true},
			card{fifteenRank, trumps, sn.NoPID, true},
			card{sixteenRank, trumps, sn.NoPID, true},
			card{seventeenRank, trumps, sn.NoPID, true},
			card{eighteenRank, trumps, sn.NoPID, true},
			card{nineteenRank, trumps, sn.NoPID, true},
			card{twentyRank, trumps, sn.NoPID, true},
			card{twentyoneRank, trumps, sn.NoPID, true},
			card{excuseRank, trumps, sn.NoPID, true},
		}
	default:
		d = nil
	}

	return pie.Shuffle(d, myRandomSource)
}
